# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'homework9' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for homework9
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'McPicker'
    pod 'LUAutocompleteView'
    pod 'Validator'
    pod 'EasyToast'
    pod 'SwiftSpinner'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'ImageLoader'
    pod 'Kingfisher'
    pod 'SearchTextField'
end
